package constants

const (
	InvalidCredentials            = "Invalid credentials"
	CouldNotGenerateToken         = "Could not generate token"
	PasswordValidationError       = "Length of Password must be greater than 8"
	UserNameValidationError       = "Length of Username must be greater than 8"
	PasswordHashingError          = "Error hashing password"
	DatabaseError                 = "Database error"
	UserAlreadyExists             = "User Name Already Exists!"
	UserNotFound                  = "User Not Found! "
	FailedToConnectDatabase       = "Failed To Connect Database !"
	ConnectionSuccess             = "Connection Success !"
	MalformedToken                = "Malformed Token !"
	TokenExpired                  = "Token is either expired or not active yet"
	InvalidToken                  = "Invalid Token !"
	UnAuthorize                   = "UnAuthorize"
	ErrorRetrevingUserFromRedis   = "Error retrieving Users from Redis"
	ErrorRetrevingStocksFromRedis = "Error retrieving Stocks from Redis"
	FailedToSerializeJSON         = "Failed to serialize users to JSON: "
	FailedToConnectRedis          = "Failed To Connect Redis"
	TransactionStarted            = "Transaction Started !"
	FailedToSetDataInRedis        = "Failed to set data in Redis: "
	ErrorInParsingDateToStr       = "Error parsing inputDateStr:"
	DateOutPutLayout              = "2006-01-02 15:04:05.000000-07"
	DateInputLayout               = "2006-01-02"
	TickerNotFound                = "Ticker Not Found!"
	UserHasNotEnoughBalance       = "User has not Enough balance !"
	NotEnoughStocks               = "Not Enough Stocks"
)
